name: Checker

on:
  schedule:
    - cron: '0 7 * * *' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.12
    - name: Install requirements #安装requests
      run: |
        pip install -r requirements.txt
        pip install requests[security]
    - name: Update links #更新
      run: |
        python checker/main.py ${{ secrets.GITHUB_TOKEN }}
        python generator/main.py
    - name: Commit & Push
      uses: action-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'output'
        force-push: 'true'
        commit-message: 'Generate Json'
        name: github-actions[bot]
        email: github-actions[bot]@noreply.github.com
